# Generated by Django 3.2.23 on 2024-04-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.CharField(default='', max_length=255, verbose_name='Email'),
        ),
    ]
