# Generated by Django 3.2.23 on 2024-04-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='telephone',
            field=models.CharField(max_length=13, verbose_name='Telefone'),
        ),
    ]
